### ISSUE TITLE
Empty result for all_speakers/all_microphones on Ubuntu OS

### ISSUE THREAD

**Issue by will46616** [bastibe/SoundCard#176]
Hi, I've installed soundcard module, but I ran soundcard.all_speakers() only get an empty list.  Is there somthing wrong on my sound device?

**Comment by bastibe** [comment]
Is there any error message?

**Comment by will46616** [comment]
I just got [] after runnning sc.all_speakers(), but I got some error message while running my code : 
Exception ignored from cffi callback <function _PulseAudio.server_info.<locals>.callback at 0x7f2a73e581f0>:
Traceback (most recent call last):
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/soundcard/pulseaudio.py", line 211, in callback
    info['default sink id'] = _ffi.string(server_info.default_sink_name).decode('utf-8')
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/cffi/api.py", line 318, in string
    return self._backend.string(cdata, maxlen)
RuntimeError: cannot use string() on <cdata 'char *' NULL>
Traceback (most recent call last):
  File "/home3/will/BandSplitRNN-Pytorch-main/src/tt/test.py", line 39, in <module>
    with sc.get_microphone(id=str(sc.default_speaker().name), include_loopback=True).recorder(samplerate=SAMPLE_RATE) as mic:
  File "/home3/will/anaconda3/envs/MUSDB2/lib/python3.9/site-packages/soundcard/pulseaudio.py", line 287, in default_speaker
    name = _pulse.server_info['default sink id']
KeyError: 'default sink id'

Is this because there's no available speaker detected?

**Comment by bastibe** [comment]
it seems that pulseaudio does not return a default_sink name. There's probably something about your pulseaudio that is not properly set up.

**Comment by will46616** [comment]
OK, thanks. I'll check my pulseaudio. Thank you for replying.

**Comment by will46616** [comment]
Hi, now I can get audio loopback with soundcard and record it, but I have another question. Is it possible to keep using loopback with soundcard module? Just like using sounddevice.InputStream().
